### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: Protocol(HandshakeIncomplete)

### ISSUE THREAD

**Issue by goldyfruit** [OscillateLabsLLC/ovos-rust-messagebus#3]
```
ovos-core-65dc9d56d9-468lp ovos-messagebus Received message: {"type":"register_vocab","data":{"entity_value":"sound track","entity_type":"common_query_openvoiceosMusickeyword","lang":"en-us","start":"sound track","end":"common_query_openvoiceosMusickeyword"},"context":{"skill_id":"common_query.openvoiceos","session":{"active_skills":[],"utterance_states":{},"session_id":"default","lang":"en-us","context":{"timeout":120,"frame_stack":[]},"site_id":"unknown","pipeline":["stop_high","converse","ocp_high","padatious_high","adapt_high","ocp_medium","fallback_high","stop_medium","adapt_medium","padatious_medium","adapt_low","common_qa","fallback_medium","fallback_low"],"location":{"city":{"code":"Lawrence","name":"Lawrence","state":{"code":"KS","name":"Kansas","country":{"code":"US","name":"United States"}}},"coordinate":{"latitude":38.971669,"longitude":-95.23525},"timezone":{"code":"America/Chicago","name":"Central Standard Time","dstOffset":3600000,"offset":-21600000}},"system_unit":"metric","time_format":"half","date_format":"MDY","is_speaking":false,"is_recording":false,"blacklisted_skills":["skill-ovos-stop.openvoiceos"],"blacklisted_intents":[]}}}
ovos-core-65dc9d56d9-468lp ovos-messagebus Received message: {"type":"register_vocab","data":{"entity_value":"soundtrack","entity_type":"common_query_openvoiceosMusickeyword","lang":"en-us","start":"soundtrack","end":"common_query_openvoiceosMusickeyword"},"context":{"skill_id":"common_query.openvoiceos","session":{"active_skills":[],"utterance_states":{},"session_id":"default","lang":"en-us","context":{"timeout":120,"frame_stack":[]},"site_id":"unknown","pipeline":["stop_high","converse","ocp_high","padatious_high","adapt_high","ocp_medium","fallback_high","stop_medium","adapt_medium","padatious_medium","adapt_low","common_qa","fallback_medium","fallback_low"],"location":{"city":{"code":"Lawrence","name":"Lawrence","state":{"code":"KS","name":"Kansas","country":{"code":"US","name":"United States"}}},"coordinate":{"latitude":38.971669,"longitude":-95.23525},"timezone":{"code":"America/Chicago","name":"Central Standard Time","dstOffset":3600000,"offset":-21600000}},"system_unit":"metric","time_format":"half","date_format":"MDY","is_speaking":false,"is_recording":false,"blacklisted_skills":["skill-ovos-stop.openvoiceos"],"blacklisted_intents":[]}}}
ovos-core-65dc9d56d9-468lp ovos-messagebus Received message: {"type":"register_vocab","data":{"entity_value":"news","entity_type":"common_query_openvoiceosNewskeyword","lang":"en-us","start":"news","end":"common_query_openvoiceosNewskeyword"},"context":{"skill_id":"common_query.openvoiceos","session":{"active_skills":[],"utterance_states":{},"session_id":"default","lang":"en-us","context":{"timeout":120,"frame_stack":[]},"site_id":"unknown","pipeline":["stop_high","converse","ocp_high","padatious_high","adapt_high","ocp_medium","fallback_high","stop_medium","adapt_medium","padatious_medium","adapt_low","common_qa","fallback_medium","fallback_low"],"location":{"city":{"code":"Lawrence","name":"Lawrence","state":{"code":"KS","name":"Kansas","country":{"code":"US","name":"United States"}}},"coordinate":{"latitude":38.971669,"longitude":-95.23525},"timezone":{"code":"America/Chicago","name":"Central Standard Time","dstOffset":3600000,"offset":-21600000}},"system_unit":"metric","time_format":"half","date_format":"MDY","is_speaking":false,"is_recording":false,"blacklisted_skills":["skill-ovos-stop.openvoiceos"],"blacklisted_intents":[]}}}
```

```
ovos-core-65dc9d56d9-468lp ovos-messagebus thread 'main' panicked at src/main.rs:86:56:
ovos-core-65dc9d56d9-468lp ovos-messagebus called `Result::unwrap()` on an `Err` value: Protocol(HandshakeIncomplete)
ovos-core-65dc9d56d9-468lp ovos-messagebus note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by goldyfruit** [comment]
With the Rust trace.

```
ovos-core-66bf8466c9-vhb2t ovos-messagebus thread 'main' panicked at src/main.rs:86:56:
ovos-core-66bf8466c9-vhb2t ovos-messagebus called `Result::unwrap()` on an `Err` value: Protocol(HandshakeIncomplete)
ovos-core-66bf8466c9-vhb2t ovos-messagebus stack backtrace:
ovos-core-66bf8466c9-vhb2t ovos-messagebus    0:     0x55b616d7ac55 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
ovos-core-66bf8466c9-vhb2t ovos-messagebus    1:     0x55b616d9acbb - core::fmt::write::hc090a2ffd6b28c4a
ovos-core-66bf8466c9-vhb2t ovos-messagebus    2:     0x55b616d7846f - std::io::Write::write_fmt::h8898bac6ff039a23
ovos-core-66bf8466c9-vhb2t ovos-messagebus    3:     0x55b616d7aa2e - std::sys_common::backtrace::print::ha96650907276675e
ovos-core-66bf8466c9-vhb2t ovos-messagebus    4:     0x55b616d7bce9 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
ovos-core-66bf8466c9-vhb2t ovos-messagebus    5:     0x55b616d7ba2d - std::panicking::default_hook::h207342be97478370
ovos-core-66bf8466c9-vhb2t ovos-messagebus    6:     0x55b616d7c183 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
ovos-core-66bf8466c9-vhb2t ovos-messagebus    7:     0x55b616d7c064 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
ovos-core-66bf8466c9-vhb2t ovos-messagebus    8:     0x55b616d7b119 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
ovos-core-66bf8466c9-vhb2t ovos-messagebus    9:     0x55b616d7bd97 - rust_begin_unwind
ovos-core-66bf8466c9-vhb2t ovos-messagebus   10:     0x55b616cf9973 - core::panicking::panic_fmt::hdc63834ffaaefae5
ovos-core-66bf8466c9-vhb2t ovos-messagebus   11:     0x55b616cf9de6 - core::result::unwrap_failed::h82b551e0ff2b2176
ovos-core-66bf8466c9-vhb2t ovos-messagebus   12:     0x55b616cfe413 - tokio::runtime::park::CachedParkThread::block_on::h9e0b1073035c6333
ovos-core-66bf8466c9-vhb2t ovos-messagebus   13:     0x55b616d1ba8e - tokio::runtime::context::runtime::enter_runtime::h9abbca00d8da8e78
ovos-core-66bf8466c9-vhb2t ovos-messagebus   14:     0x55b616d101eb - tokio::runtime::runtime::Runtime::block_on::h261dcfa7449a1663
ovos-core-66bf8466c9-vhb2t ovos-messagebus   15:     0x55b616d155c4 - ovos_messagebus::main::hf06a27141427413e
ovos-core-66bf8466c9-vhb2t ovos-messagebus   16:     0x55b616d17563 - std::sys_common::backtrace::__rust_begin_short_backtrace::h511a26050a1aee43
ovos-core-66bf8466c9-vhb2t ovos-messagebus   17:     0x55b616d0e899 - std::rt::lang_start::{{closure}}::h127381cb1f4a9acf
ovos-core-66bf8466c9-vhb2t ovos-messagebus   18:     0x55b616d74f20 - std::rt::lang_start_internal::h3ed4fe7b2f419135
ovos-core-66bf8466c9-vhb2t ovos-messagebus   19:     0x55b616d15695 - main
ovos-core-66bf8466c9-vhb2t ovos-messagebus   20:     0x7f67fa40509b - __libc_start_main
ovos-core-66bf8466c9-vhb2t ovos-messagebus   21:     0x55b616cfa04a - _start
ovos-core-66bf8466c9-vhb2t ovos-messagebus   22:                0x0 - <unknown>
```

**Comment by mikejgray** [comment]
We identified that this is the Kubernetes healthcheck, which makes a standard HTTP request and not a websockets handshake. I've added some additional error handling to make sure this doesn't cause a panic, but rather logs out what's going on.
